### ISSUE TITLE
.

### ISSUE THREAD

**Issue by ghost** [ALEXMORF/the-dark-dungeon#11]

**Comment by ALEXMORF** [comment]
You are getting a little aggressive there mate. Hi vlad, thank you for telling me about this new trend. I definitely agree with you on the importance of cross-platformness of the code. However, if you look closely at my code, you will see that it's barely coupled with the windows API. The large chunk of code that actually matters are written independently from any library or platform. My fast_main.cpp is just  a cross-platform platform layer with a little bit of win32 function call. If you want, maybe port my game by adding changes to my fast_main.cpp so it can be compiled on linux? ;)

**Comment by ALEXMORF** [comment]
Retard

**Comment by ALEXMORF** [comment]
retard

**Comment by ALEXMORF** [comment]
lintard
