### ISSUE TITLE
Could you add a license, please?

### ISSUE THREAD

**Issue by jacmoe** [ALEXMORF/the-dark-dungeon#14]
I want to base a project on your code, but it has no license.

I would be happy if you could add a license to it, and I would be even happier if that license was permissive, like BSD or MIT.

Thanks :)

Really cool level generation code,  btw!

**Comment by ALEXMORF** [comment]
Thank you for the compliments! I already added an MIT licence like you requested. I hope my code isn't too messy to deal with, good luck.

**Comment by jacmoe** [comment]
Thanks a lot for the licensing!
Your code is probably not messier than my own code ;p
